# Generated by Django 3.2.8 on 2024-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_destination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='amt_paid',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='passenger',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
