# Generated by Django 3.2.8 on 2024-04-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20240430_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='amt_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
