# Generated by Django 4.2.13 on 2024-05-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_passenger_amt_paid_alter_passenger_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.destination'),
        ),
    ]
